# Generated by Django 4.2 on 2025-05-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tag',
            new_name='tags',
        ),
    ]
