# Generated by Django 4.2 on 2025-05-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.URLField(unique=True),
        ),
    ]
